
forest:
  timeout: 3333
  log-enabled: true
  log-response-content: true
  backend: okhttp3
  variables:
    giteeUrl: https://gitee.com
    idServiceUrl: https://www.12306.cn


myfile:
  uploadPath: D:\TestUpload\target
